# Project o1

### Importing "PS4_GamesSales.csv" file 

In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Load the CSV file
df = pd.read_csv("PS4_GamesSales.csv", encoding='ISO-8859-1')
print("dataset load successfully")

dataset load successfully


In [2]:
# Display shape of the dataset
print("Dataset Shape (Rows, Columns):")
df.shape


Dataset Shape (Rows, Columns):


(1034, 9)

In [3]:
# Display dataset information
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1034 entries, 0 to 1033
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Game           1034 non-null   object 
 1   Year           825 non-null    float64
 2   Genre          1034 non-null   object 
 3   Publisher      825 non-null    object 
 4   North America  1034 non-null   float64
 5   Europe         1034 non-null   float64
 6   Japan          1034 non-null   float64
 7   Rest of World  1034 non-null   float64
 8   Global         1034 non-null   float64
dtypes: float64(6), object(3)
memory usage: 72.8+ KB


In [4]:
# Display column names
df.columns


Index(['Game', 'Year', 'Genre', 'Publisher', 'North America', 'Europe',
       'Japan', 'Rest of World', 'Global'],
      dtype='object')

In [5]:
# Display first 5 rows
df.head()


Game    Year             Genre       Publisher  \
0         Grand Theft Auto V  2014.0            Action  Rockstar Games   
1  Call of Duty: Black Ops 3  2015.0           Shooter      Activision   
2      Red Dead Redemption 2  2018.0  Action-Adventure  Rockstar Games   
3         Call of Duty: WWII  2017.0           Shooter      Activision   
4                    FIFA 18  2017.0            Sports       EA Sports   

   North America  Europe  Japan  Rest of World  Global  
0           6.06    9.71   0.60           3.02   19.39  
1           6.18    6.05   0.41           2.44   15.09  
2           5.26    6.21   0.21           2.26   13.94  
3           4.67    6.21   0.40           2.12   13.40  
4           1.27    8.64   0.15           1.73   11.80

### Check null values, drop then and add new cleaned data in null value drop.csv

In [6]:
# Check for missing values in all columns
missing_values = df.isnull().sum()

# Display missing values information
print("Missing values in each column:")
print(missing_values)

Missing values in each column:
Game               0
Year             209
Genre              0
Publisher        209
North America      0
Europe             0
Japan              0
Rest of World      0
Global             0
dtype: int64


In [7]:
# Check number of duplicate rows
duplicate_values = df.duplicated().sum()
print("duplicate values", duplicate_values)

# Remove duplicate rows
df.drop_duplicates(inplace=True)

print("Duplicate rows removed.")


duplicate values 0
Duplicate rows removed.


In [8]:
# Fill missing values in 'Year' with the mean year (converted to an integer)
df['Year'].fillna(int(df['Year'].mean()), inplace=True)

# Fill missing values in 'Publisher' with the mode (most frequent value)
df['Publisher'].fillna(df['Publisher'].mode()[0], inplace=True)

# Save the cleaned DataFrame to a new CSV file
cleaned_file_path = 'cleaned_file.csv'  # Replace with the desired path for the cleaned file
df.to_csv(cleaned_file_path, index=False)

print(f"Missing values in 'Year' filled with mean (as integer) and in 'Publisher' filled with mode. Cleaned data saved to {cleaned_file_path}.")


Missing values in 'Year' filled with mean (as integer) and in 'Publisher' filled with mode. Cleaned data saved to cleaned_file.csv.


### Importing new cleaned data file and work in it

In [9]:
df = pd.read_csv('cleaned_file.csv')
df.head()

Game    Year             Genre       Publisher  \
0         Grand Theft Auto V  2014.0            Action  Rockstar Games   
1  Call of Duty: Black Ops 3  2015.0           Shooter      Activision   
2      Red Dead Redemption 2  2018.0  Action-Adventure  Rockstar Games   
3         Call of Duty: WWII  2017.0           Shooter      Activision   
4                    FIFA 18  2017.0            Sports       EA Sports   

   North America  Europe  Japan  Rest of World  Global  
0           6.06    9.71   0.60           3.02   19.39  
1           6.18    6.05   0.41           2.44   15.09  
2           5.26    6.21   0.21           2.26   13.94  
3           4.67    6.21   0.40           2.12   13.40  
4           1.27    8.64   0.15           1.73   11.80

###  Select numeric data

In [10]:
# Select only numeric columns for NumPy operations
numeric_df = df.select_dtypes(include=[np.number])

numeric_df.head()


Year  North America  Europe  Japan  Rest of World  Global
0  2014.0           6.06    9.71   0.60           3.02   19.39
1  2015.0           6.18    6.05   0.41           2.44   15.09
2  2018.0           5.26    6.21   0.21           2.26   13.94
3  2017.0           4.67    6.21   0.40           2.12   13.40
4  2017.0           1.27    8.64   0.15           1.73   11.80

### Convert pandas dataframe to numPy array

In [11]:
# Convert DataFrame to NumPy array
data_array = numeric_df.values

# Display array shape
print(data_array.shape)

#check value
print(type(numeric_df))
print(type(data_array))


(1034, 6)
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


### NumPy array operations

In [12]:
# Add 5 to each element
array_plus_5 = data_array + 5

# Multiply each element by 2
array_times_2 = data_array * 2

print("NumPy array operations completed.")


NumPy array operations completed.


### NumPy Statistics

In [13]:
# Calculate mean of numeric columns
mean_values = np.mean(data_array, axis=0)

mean_values


array([2.01577079e+03, 2.04613153e-01, 2.48713733e-01, 3.36363636e-02,
       8.90135397e-02, 5.76054159e-01])

In [14]:
# Calculate median of numeric columns
median_values = np.median(data_array, axis=0)

median_values


array([2.016e+03, 2.000e-02, 0.000e+00, 0.000e+00, 1.000e-02, 6.000e-02])

In [15]:
# Calculate standard deviation of numeric columns
std_values = np.std(data_array, axis=0)

std_values


array([1.22224622, 0.56319867, 0.78511157, 0.10829132, 0.2492895 ,
       1.58276785])

In [16]:
print("Task 1: Data Handling with NumPy & Pandas completed successfully!")


Task 1: Data Handling with NumPy & Pandas completed successfully!
